src/views/blog.py

from operator import pos
from flask import(
    render_template, Blueprint, flash, g, redirect, request, url_for
)

from werkzeug.exceptions import abort

from src.models.post import Post
from src.models.user import User

from src.views.auth import login_required

from src import db

blog = Blueprint('blog', __name__)

#Obtner un ususario
def get_user(id):
    user = User.query.get_or_404(id)
    return user

@blog.route("/")
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template('blog/index.html', posts = posts, get_user=get_user)

#Registrar un post 
@blog.route('/blog/create', methods=('GET','POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/create.html')

def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe.')

    if check_author and post.author != g.user.id:
        abort(404)
    
    return post

#Update post 
@blog.route('/blog/update/<int:id>', methods=('GET','POST'))
@login_required
def update(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/update.html', post=post)

#Eliminar un post
@blog.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.index'))

src/templates/blog/create.html

{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Crear una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10"></textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}

src/templates/blog/index.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Publicaciones {% endblock %}</h2>
    {% if g.user %}
        <a href="{{ url_for('blog.create') }}">Nueva Publicación</a>
    {% endif%}
{% endblock %}

{% block content %}

{% for post in posts %}
    <article>
        <header>
            <div>
               <h1>{{ post.title }}</h1>
                <div class="about">
                    Publicado por {{ get_user(post.author).username}}
                    el {{ post.created.strftime('%Y-%m-%d') }}
                </div> 
            </div>
            <div>
                {% if g.user.id == post.author %}
                    <a href="{{ url_for('blog.update', id=post.id) }}">Editar</a>
                    <a href="{{ url_for('blog.delete', id=post.id) }}">Eliminar</a>
                {% endif %}
            </div>
        </header>
        <div>
            <p>{{ post.body }}</p>
        </div>
    </article>
{% endfor %}

{% endblock %}

src/templates/blog/update.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Actualizar una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" value="{{ post.title }}" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10">{{ post.body }}</textarea>
        <input type="submit", value="Guardar">
    </form>
{% endblock %}